Feature/api
future-stardust/url-shrtnr-vxjsu2 pull request #5
Opened 2021-03-12 12:24 UTC by p3rsik

Please look at basic handler implementation[WIP]. I'll add Auth a bit later.

2021-03-12 14:26 UTC, dedifferentiator requested changes

2021-03-12 14:28 UTC, dedifferentiator commented
Also I would like to see tests and code documentation, without it it's pretty hard to reason about correctness of the module :)

2021-03-12 20:31 UTC, dedifferentiator requested changes

2021-03-12 20:31 UTC, dedifferentiator commented on src/Server/Handler/Urls.hs
> +               else ""
Would be nice to separate `shortenWithAlphabet` from `shortenH`, so we could use it somewhere apart from this specific handler

2021-03-12 20:31 UTC, dedifferentiator commented on src/Server/Server.hs
> +          :<|> redirectH
```suggestion
serverT :: ServerT API HandlerT
serverT = signUpH
     :<|> signInH
     :<|> signOutH
     :<|> shortenH
     :<|> listUrlsH
     :<|> deleteUrlH
     :<|> redirectH
```

2021-03-12 23:37 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +import           Server.API.Redirect
?

2021-03-12 23:38 UTC, p3rsik commented on test/Server/Handler/RedirectSpec.hs
> +import           Server.API.Redirect
!

2021-03-12 23:38 UTC, p3rsik commented on test/Server/Handler/RedirectSpec.hs
> +import           Server.API.Redirect
Fixed

2021-03-12 23:44 UTC, dedifferentiator requested changes

2021-03-12 23:44 UTC, dedifferentiator commented on test/Server/Handler/UrlsSpec.hs
> +        token = Just $ Token "test@test.com\ntestpasswd"
move pre-test setup into the separate function

2021-03-13 12:52 UTC, dedifferentiator requested changes

2021-03-13 12:52 UTC, dedifferentiator commented on src/Server/Handler/Users.hs
> +signInH cookies jwts u@T.User{..} = do
```suggestion
signInH :: CookieSettings -> JWTSettings -> T.User
  -> HandlerT (Headers '[Header "Set-Cookie" SetCookie, Header "Set-Cookie" SetCookie] NoContent)
signInH cookies jwts u@T.User{..} = do
```

2021-03-13 12:52 UTC, dedifferentiator commented on src/Server/Handler/Users.hs
> +signInH cookies jwts u@T.User{..} = do
I think it would be noice to use a separate type for headers

2021-03-13 12:52 UTC, dedifferentiator commented on src/Server/Handler/Users.hs
> +signOutH _       _                 = throwError err401
Same here, a separate type

2021-03-13 12:52 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +          url = D.Url "original_test" "test_alias"
```suggestion
      let username  = "test@test.com"
          hash      = "testpasswd"
          originUrl = "original_test"
          aliasUrl  = "testalias"    
      let usr = D.User username [] hash
          url = D.Url originUrl aliasUrl
```

2021-03-13 12:52 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +          url = D.Url "original_test" "test_alias"
Put fields' names in additional let clause, so they could be accessed from the following describe-it scope without being hardcoded every time

2021-03-13 12:52 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +              && any (\(hn, hb) -> hn == "Location" && hb == "original_test") responseHeaders -- and Location with "original_test"
Here `original_test` shouldn't be hardcoded, see previous comment on `WithUserApp`

2021-03-13 12:52 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +              && any (\(hn, hb) -> hn == "Location" && hb == "original_test") responseHeaders -- and Location with "original_test"
```suggestion
              -- status code should be 302
              statusCode responseStatusCode == 302
              -- hn and hb should be the same as the values in db
              && any (\(hn, hb) -> hn == "Location" && hb == "original_test") responseHeaders
```

2021-03-13 12:52 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +              && any (\(hn, hb) -> hn == "Location" && hb == "original_test") responseHeaders -- and Location with "original_test"
Also it's not really clear what `hn` and `hb` are, as I understand `hb` is original url, but that's quite hard to understand from function name, and what `hn` and `"Location"` are I don't understand at all :)

2021-03-13 12:52 UTC, dedifferentiator commented on test/Server/Handler/UrlsSpec.hs
> +        shortenUrl :<|> listUrls :<|> deleteUrl = client api (BasicAuthData "test@test.com" "testpasswd")
```suggestion
        shortenUrl :<|> listUrls :<|> deleteUrl =
            client api (BasicAuthData "test@test.com" "testpasswd")
```

2021-03-13 12:55 UTC, p3rsik commented on test/Server/Handler/RedirectSpec.hs
> +              && any (\(hn, hb) -> hn == "Location" && hb == "original_test") responseHeaders -- and Location with "original_test"
(hn, hb) - (HeaderHame, HeaderBody)
It's library related, all I can do is add comment here

2021-03-13 12:57 UTC, dedifferentiator commented on test/Server/Handler/RedirectSpec.hs
> +              && any (\(hn, hb) -> hn == "Location" && hb == "original_test") responseHeaders -- and Location with "original_test"
Oh, I see, that makes sense!

2021-03-14 11:29 UTC, dedifferentiator requested changes

2021-03-14 11:29 UTC, dedifferentiator commented on src/Server/API/Urls.hs
> +type DeleteUrl = "urls" :> Capture "alias" Text :> Delete '[JSON] NoContent
Should return `204` status code on success, instead of current `200`

2021-03-14 14:10 UTC, dedifferentiator commented on src/Server/Types/Util.hs
> +                        ESUrlNExist -> err500 { errBody = "Shortened url doesn't exist" }
```suggestion
dbToServerError :: DBError -> ServerError
dbToServerError = \case
    EUserExist  -> err409 { errBody = "User with such email already exists" }
    EUserNExist -> err404 { errBody = "User with such email doesn't exist"  }
    EUserNil    -> err406 { errBody = "Email or passw is empty"             }
    EUrlNil     -> err406 { errBody = "Shortened or original url are empty" }
    EUrlExist   -> err409 { errBody = "Url already exists"                  }
    EUrlNExist  -> err404 { errBody = "Url doesn't found"                   }
    ESUrlNil    -> err500 { errBody = "Shortened url is null"               }
    ESUrlExist  -> err500 { errBody = "Shortened url already exists"        }
    ESUrlNExist -> err500 { errBody = "Shortened url doesn't exist"         }
```

2021-03-14 14:10 UTC, dedifferentiator commented on src/Server/Types/Util.hs
> +                        ESUrlNExist -> err500 { errBody = "Shortened url doesn't exist" }
Might look prettier if spiced up with `LambdaCase`

2021-03-14 17:44 UTC, dedifferentiator requested changes

2021-03-14 17:44 UTC, dedifferentiator commented on src/Server/Types/Util.hs
> +                        EUrlNExist  -> err404 { errBody = "Url doesn't found" }
```suggestion
                        EUrlNExist  -> err404 { errBody = "Url is not found" }
```

2021-03-15 12:41 UTC, dedifferentiator commented
@p3rsik add docs, fix remaining RC and we're ready to merge!

2021-03-15 16:10 UTC, p3rsik commented
done!11!

2021-03-15 16:20 UTC, dedifferentiator requested changes

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Auth.hs
> +{-# OPTIONS_GHC -Wno-orphans #-}
```suggestion
{-# LANGUAGE DataKinds #-}

{-# OPTIONS_GHC -Wno-orphans #-}
```

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Handler/Urls.hs
> +-- | Handler used for /urls shorten endpoint
```suggestion
-- | Handler for /urls/shorten endpoint
```

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Handler/Urls.hs
> +-- | Handler used for /urls list urls endpoint
```suggestion
-- | Handler for /urls endpoint, which lists urls
```

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Handler/Urls.hs
> +-- | Handler used for /urls delete endpoint
```suggestion
-- | Handler for /urls endpoint, which deletes url
```

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Server.hs
> +-- | Used to start the service up
```suggestion
-- | Start up the service
```

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Types/AppCtx.hs
> +-- | Context for Handler's used in ReaderT as configuratoin
```suggestion
-- | Context for Handler's used in ReaderT as configuration
```

2021-03-15 16:20 UTC, dedifferentiator commented on src/Server/Types/Handler.hs
> +-- | Used to convert custom HandlerT to the Servant Handler
```suggestion
-- | Convert custom HandlerT to Servant Handler
```

2021-03-15 17:04 UTC, p3rsik commented on src/Server/Auth.hs
> +{-# OPTIONS_GHC -Wno-orphans #-}
Outdated suggestions cannot be aplied, whatever that means. Looking at how there are only 2 extensions here, I think it would be fine to leave it as it is.

2021-03-15 17:04 UTC, p3rsik commented on src/Server/Auth.hs
> +{-# OPTIONS_GHC -Wno-orphans #-}
If yes, please resolve converstaion.

2021-03-15 17:14 UTC, dedifferentiator commented on src/Server/Auth.hs
> +{-# OPTIONS_GHC -Wno-orphans #-}
agreed

2021-03-15 17:25 UTC, dedifferentiator commented
LGTM

2021-03-15 17:25 UTC, dedifferentiator commented
Thanks, merging!

2021-03-15 17:26 UTC, merged